package ouau
Opcodes :: enum {
	MOVE,
	LOADK,
	LOADBOOL,
	LOADNIL,
	GETUPVAL,
	GETGLOBAL,
	GETTABLE,
	SETGLOBAL,
	SETUPVAL,
	SETTABLE,
	NEWTABLE,
	SELF,
	ADD,
	SUB,
	MUL,
	DIV,
	POW,
	UNM,
	NOT,
	CONCAT,
	JMP,
	EQ,
	LT,
	LE,
	TEST,
	CALL,
	TAILCALL,
	RETURN,
	FORLOOP,
	TFORLOOP,
	TFORPREP,
	SETLIST,
	SETLISTO,
	CLOSE,
	CLOSURE,
}
// OP | A | B | C OR:
// OP | A | Bx OR:
// OP | A | sBx
// Each defn set {Move, 2|0|0}
Definition :: struct {
	name:  string,
	width: []int,
}
@(rodata)
Definition__Table__ := [Opcodes]Definition {
	.MOVE      = {"MOVE", {2}},
	.LOADK     = {"LOADK", {2}},
	.LOADBOOL  = {"LOADBOOL", {3}},
	.LOADNIL   = {"LOADNIL", {2}},
	.GETUPVAL  = {"GETUPVAL", {2}},
	.GETGLOBAL = {"GETGLOBAL", {2}},
	.GETTABLE  = {"GETTABLE", {3}},
	.SETGLOBAL = {"SETGLOBAL", {2}},
	.SETUPVAL  = {"SETUPVAL", {2}},
	.SETTABLE  = {"SETTABLE", {3}},
	.NEWTABLE  = {"NEWTABLE", {3}},
	.SELF      = {"SELF", {3}},
	.ADD       = {"ADD", {3}},
	.SUB       = {"SUB", {3}},
	.MUL       = {"MUL", {3}},
	.DIV       = {"DIV", {3}},
	.POW       = {"POW", {3}},
	.UNM       = {"UNM", {2}},
	.NOT       = {"NOT", {2}},
	.CONCAT    = {"CONCAT", {3}},
	.JMP       = {"JMP", {1}},
	.EQ        = {"EQ", {3}},
	.LT        = {"LT", {3}},
	.LE        = {"LE", {3}},
	.TEST      = {"TEST", {3}},
	.CALL      = {"CALL", {3}},
	.TAILCALL  = {"TAILCALL", {3}},
	.RETURN    = {"RETURN", {2}},
	.FORLOOP   = {"FORLOOP", {2}},
	.TFORLOOP  = {"TFORLOOP", {2}},
	.TFORPREP  = {"TFORPREP", {2}},
	.SETLIST   = {"SETLIST", {2}},
	.SETLISTO  = {"SETLISTO", {2}},
	.CLOSE     = {"CLOSE", {1}},
	.CLOSURE   = {"CLOSURE", {2}},
}

